on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Test Organization
