on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - id: repository
      run: $env:REPOSITORY_NAME=${env:GITHUB_REPOSITORY}.replace(${env:GITHUB_REPOSITORY_OWNER}, "")
      shell: powershell

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme

    - name: Build
      run: |
        sphinx-quickstart -p $env:REPOSITORY_NAME -a $env:GITHUB_ACTOR -q .\docs
        sphinx-apidoc .\docs .\$env:REPOSITORY_NAME
        .\docs\make.bat html
      shell: powershell

    - name: Run a one-line script
      run: dir .\docs\_build
